version: '3.1'

services:
  wordpress:
    depends_on:
      - db
    links:
      - db
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      backend:
        ipv4_address: 172.16.238.201

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.238.200

volumes:
  wordpress:
  db:
  
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24